"""Repository contract."""
from __future__ import annotations

from typing import Protocol

from funnel.models.job import JobDescription
from funnel.models.profile import CandidateProfile


class CandidateRepository(Protocol):
    def upsert(self, profile: CandidateProfile) -> None: ...
    def get(self, candidate_id: str) -> CandidateProfile | None: ...
    def list(self) -> list[CandidateProfile]: ...


class JobRepository(Protocol):
    def upsert(self, job: JobDescription) -> None: ...
    def get(self, job_id: str) -> JobDescription | None: ...
    def list(self) -> list[JobDescription]: ...
